//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donordata
    {
        public int D_id { get; set; }
        public string Dname { get; set; }
        public string Dusername { get; set; }
        public string Dpassword { get; set; }
        public string DPhone { get; set; }
        public string Ddistrict { get; set; }
        public string Daddress { get; set; }
        public string Dthana { get; set; }
        public string Bbloodgroup { get; set; }
        public Nullable<System.DateTime> DdonateDate { get; set; }
        public Nullable<bool> Dactive { get; set; }
    }
}
